<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $arrPermiss = [
        //     "master"=>
        //     [
        //         "ler" => [
        //               "painel" => "s",
        //               "cad-conteudo" => "s",
        //               "posts" => "s",
        //               "pages" => "s",
        //               "documents" => "s",
        //               "leis" => "s",
        //               "concursos" => "s",
        //               "decretos" => "s",
        //               "diarios" => "s",
        //               "portarias" => "s",
        //               "convenios" => "s",
        //               "box-archives" => "s",
        //               "archives" => "s",
        //               "archives_category" => "s",
        //               "admin.sic" => "s",
        //               "sic" => "s",
        //               "licitacoes" => "s",
        //               "biddings" => "s",
        //               "biddings_categories" => "s",
        //               "biddings_phases" => "s",
        //               "biddings_genres" => "s",
        //               "biddings_types" => "s",
        //               "financeiro" => "s",
        //               "extrato" => "s",
        //               "receitas" => "s",
        //               "despesas" => "s",
        //               "config" => "s",
        //               "documentos" => "s",
        //               "sistema" => "s",
        //               "users" => "s",
        //               "fornecedores" => "s",
        //               "cat_receitas" => "s",
        //               "cat_despesas" => "s",
        //               "f_pagamento" => "s",
        //               "contas" => "s",
        //               "permissions" => "s",
        //               "tags" => "s",
        //               "qoptions" => "s",
        //               "enterprise" => "s"
        //            ],
        //         "create" => [
        //                  "posts" => "s",
        //                  "pages" => "s",
        //                  "leis" => "s",
        //                  "concursos" => "s",
        //                  "decretos" => "s",
        //                  "diarios" => "s",
        //                  "portarias" => "s",
        //                  "convenios" => "s",
        //                  "archives" => "s",
        //                  "archives_category" => "s",
        //                  "sic" => "s",
        //                  "biddings" => "s",
        //                  "biddings_categories" => "s",
        //                  "biddings_phases" => "s",
        //                  "biddings_genres" => "s",
        //                  "biddings_types" => "s",
        //                  "extrato" => "s",
        //                  "receitas" => "s",
        //                  "despesas" => "s",
        //                  "documentos" => "s",
        //                  "sistema" => "s",
        //                  "users" => "s",
        //                  "fornecedores" => "s",
        //                  "cat_receitas" => "s",
        //                  "cat_despesas" => "s",
        //                  "f_pagamento" => "s",
        //                  "contas" => "s",
        //                  "permissions" => "s",
        //                  "tags" => "s",
        //                  "qoptions" => "s",
        //                  "enterprise" => "s"
        //               ],
        //         "update" => [
        //                     "posts" => "s",
        //                     "pages" => "s",
        //                     "leis" => "s",
        //                     "concursos" => "s",
        //                     "decretos" => "s",
        //                     "diarios" => "s",
        //                     "portarias" => "s",
        //                     "convenios" => "s",
        //                     "archives" => "s",
        //                     "archives_category" => "s",
        //                     "sic" => "s",
        //                     "biddings" => "s",
        //                     "biddings_categories" => "s",
        //                     "biddings_phases" => "s",
        //                     "biddings_genres" => "s",
        //                     "biddings_types" => "s",
        //                     "extrato" => "s",
        //                     "receitas" => "s",
        //                     "despesas" => "s",
        //                     "documentos" => "s",
        //                     "sistema" => "s",
        //                     "users" => "s",
        //                     "fornecedores" => "s",
        //                     "cat_receitas" => "s",
        //                     "cat_despesas" => "s",
        //                     "f_pagamento" => "s",
        //                     "contas" => "s",
        //                     "permissions" => "s",
        //                     "tags" => "s",
        //                     "qoptions" => "s",
        //                     "enterprise" => "s"
        //                  ],
        //         "delete" => [
        //                        "posts" => "s",
        //                        "pages" => "s",
        //                        "leis" => "s",
        //                        "concursos" => "s",
        //                        "decretos" => "s",
        //                        "diarios" => "s",
        //                        "portarias" => "s",
        //                        "convenios" => "s",
        //                        "archives" => "s",
        //                        "archives_category" => "s",
        //                        "sic" => "s",
        //                        "biddings" => "s",
        //                        "biddings_categories" => "s",
        //                        "biddings_phases" => "s",
        //                        "biddings_genres" => "s",
        //                        "biddings_types" => "s",
        //                        "extrato" => "s",
        //                        "receitas" => "s",
        //                        "despesas" => "s",
        //                        "documentos" => "s",
        //                        "sistema" => "s",
        //                        "users" => "s",
        //                        "fornecedores" => "s",
        //                        "cat_receitas" => "s",
        //                        "cat_despesas" => "s",
        //                        "f_pagamento" => "s",
        //                        "contas" => "s",
        //                        "permissions" => "s",
        //                        "tags" => "s",
        //                        "qoptions" => "s",
        //                        "enterprise" => "s"
        //                     ],
        //         "ler_arquivos" => [
        //                           "posts" => "s",
        //                           "pages" => "s",
        //                           "leis" => "s",
        //                           "concursos" => "s",
        //                           "decretos" => "s",
        //                           "diarios" => "s",
        //                           "portarias" => "s",
        //                           "convenios" => "s",
        //                           "archives" => "s",
        //                           "archives_category" => "s",
        //                           "sic" => "s",
        //                           "biddings" => "s",
        //                           "biddings_categories" => "s",
        //                           "biddings_phases" => "s",
        //                           "biddings_genres" => "s",
        //                           "biddings_types" => "s",
        //                           "extrato" => "s",
        //                           "receitas" => "s",
        //                           "despesas" => "s",
        //                           "documentos" => "s",
        //                           "sistema" => "s",
        //                           "users" => "s",
        //                           "fornecedores" => "s",
        //                           "cat_receitas" => "s",
        //                           "cat_despesas" => "s",
        //                           "f_pagamento" => "s",
        //                           "contas" => "s",
        //                           "permissions" => "s",
        //                           "tags" => "s",
        //                           "qoptions" => "s",
        //                           "enterprise" => "s"
        //                        ]
        //     ],
        //     "admin"=>
        //     [
        //         "ler" => [
        //               "painel" => "s",
        //               "cad-conteudo" => "s",
        //               "posts" => "s",
        //               "pages" => "s",
        //               "documents" => "s",
        //               "leis" => "s",
        //               "concursos" => "s",
        //               "decretos" => "s",
        //               "diarios" => "s",
        //               "portarias" => "s",
        //               "convenios" => "s",
        //               "admin.sic" => "s",
        //               "sic" => "s",
        //               "licitacoes" => "s",
        //               "biddings" => "s",
        //               "biddings_categories" => "s",
        //               "biddings_phases" => "s",
        //               "biddings_genres" => "s",
        //               "biddings_types" => "s",
        //               "config" => "s",
        //               "sistema" => "s",
        //               "users" => "s"
        //            ],
        //         "create" => [
        //                  "posts" => "s",
        //                  "pages" => "s",
        //                  "leis" => "s",
        //                  "concursos" => "s",
        //                  "decretos" => "s",
        //                  "diarios" => "s",
        //                  "portarias" => "s",
        //                  "convenios" => "s",
        //                  "sic" => "s",
        //                  "biddings" => "s",
        //                  "biddings_categories" => "s",
        //                  "biddings_phases" => "s",
        //                  "biddings_genres" => "s",
        //                  "biddings_types" => "s",
        //                  "documentos" => "s",
        //                  "sistema" => "s",
        //                  "users" => "s",
        //                  "permissions" => "s",
        //                  "tags" => "s",
        //                  "qoptions" => "s"
        //               ],
        //         "update" => [
        //                     "posts" => "s",
        //                     "pages" => "s",
        //                     "leis" => "s",
        //                     "concursos" => "s",
        //                     "decretos" => "s",
        //                     "diarios" => "s",
        //                     "portarias" => "s",
        //                     "convenios" => "s",
        //                     "sic" => "s",
        //                     "biddings" => "s",
        //                     "biddings_categories" => "s",
        //                     "biddings_phases" => "s",
        //                     "biddings_genres" => "s",
        //                     "biddings_types" => "s",
        //                     "documentos" => "s",
        //                     "sistema" => "s",
        //                     "users" => "s",
        //                     "permissions" => "s",
        //                     "tags" => "s",
        //                     "qoptions" => "s"
        //                  ],
        //         "delete" => [
        //                        "posts" => "s",
        //                        "pages" => "s",
        //                        "leis" => "s",
        //                        "concursos" => "s",
        //                        "decretos" => "s",
        //                        "diarios" => "s",
        //                        "portarias" => "s",
        //                        "convenios" => "s",
        //                        "sic" => "s",
        //                        "biddings" => "s",
        //                        "biddings_categories" => "s",
        //                        "biddings_phases" => "s",
        //                        "biddings_genres" => "s",
        //                        "biddings_types" => "s",
        //                        "documentos" => "s",
        //                        "sistema" => "s",
        //                        "users" => "s",
        //                        "permissions" => "s",
        //                        "tags" => "s",
        //                        "qoptions" => "s"
        //                     ],
        //         "ler_arquivos" => [
        //                           "posts" => "s",
        //                           "pages" => "s",
        //                           "leis" => "s",
        //                           "concursos" => "s",
        //                           "decretos" => "s",
        //                           "diarios" => "s",
        //                           "portarias" => "s",
        //                           "convenios" => "s",
        //                           "sic" => "s",
        //                           "biddings" => "s",
        //                           "biddings_categories" => "s",
        //                           "biddings_phases" => "s",
        //                           "biddings_genres" => "s",
        //                           "biddings_types" => "s",
        //                           "documentos" => "s",
        //                           "sistema" => "s",
        //                           "users" => "s",
        //                           "permissions" => "s",
        //                           "tags" => "s",
        //                           "qoptions" => "s"
        //                        ]
        //      ],
        // ];
        // Permission::truncate();
        // DB::table('permissions')->insert([
        //     [
        //         'name'=>'Master',
        //         'redirect_login'=>'/admin/home',
        //         'description'=>'Desenvolvedores',
        //         'active'=>'s',
        //         'id_menu'=>json_encode($arrPermiss['master']),
        //     ],
        //     [
        //         'name'=>'Adminstrador',
        //         'redirect_login'=>'/admin/home',
        //         'description'=>'Adiminstradores do sistema',
        //         'active'=>'s',
        //         'id_menu'=>json_encode($arrPermiss['admin']),
        //     ],
        //     [
        //         'name'=>'Gerente',
        //         'redirect_login'=>'/admin/home',
        //         'description'=>'Gerente do sistema menos que administrador secundário',
        //         'active'=>'s',
        //         'id_menu'=>json_encode([]),
        //     ],
        //     [
        //         'name'=>'Escritório1',
        //         'redirect_login'=>'/admin/home',
        //         'description'=>'Pessoas do escritório',
        //         'active'=>'s',
        //         'id_menu'=>json_encode([]),
        //     ],
        //     [
        //         'name'=>'Escritório2',
        //         'redirect_login'=>'/admin/home',
        //         'description'=>'Pessoas do escritório',
        //         'active'=>'s',
        //         'id_menu'=>json_encode([]),
        //     ],
        //     [
        //         'name'=>'Servidores',
        //         'redirect_login'=>'/admin/home',
        //         'description'=>'Servidores publicos',
        //         'active'=>'s',
        //         'id_menu'=>json_encode([]),
        //     ],
        //     [
        //         'name'=>'Fornecedores',
        //         'redirect_login'=>'/admin/home',
        //         'description'=>'Fornecedores de serviços',
        //         'active'=>'s',
        //         'id_menu'=>json_encode([]),
        //     ],
        //     [
        //         'name'=>'Internautas',
        //         'redirect_login'=>'/internautas',
        //         'description'=>'Somente Internautas, Sem privilêgios de administração acesso a área restrita do site','active'=>'s',
        //         'id_menu'=>json_encode([]),
        //     ],
        // ]);
        $arrPermiss = [
            "master"=>
            array (
                'ler' =>
                array (
                  'painel' => 's',
                  'cad-produtos' => 's',
                  'os' => 's',
                  'produtos' => 's',
                  'cad-orcamentos' => 's',
                  'orcamento' => 's',
                  'orcamentos' => 's',
                  'ger-site' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'config' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ),
                'create' =>
                array (
                  'os' => 's',
                  'produtos' => 's',
                  'orcamento' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ),
                'update' =>
                array (
                  'os' => 's',
                  'produtos' => 's',
                  'orcamento' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ),
                'delete' =>
                array (
                  'os' => 's',
                  'produtos' => 's',
                  'orcamento' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ),
                'ler_arquivos' =>
                array (
                  'os' => 's',
                  'produtos' => 's',
                  'orcamento' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ),
            ),
            "admin"=>
            [
                'ler' => [
                  'painel' => 's',
                  'produtos' => 's',
                  'cad-orcamentos' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'config' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                ],
                'create' => [
                  'produtos' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ],
                'update' => [
                  'produtos' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ],
                'delete' => [
                  'produtos' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ],
                'ler_arquivos' => [
                  'produtos' => 's',
                  'orcamentos' => 's',
                  'paginas' => 's',
                  'menus' => 's',
                  'componentes' => 's',
                  'categorias' => 's',
                  'documentos' => 's',
                  'sistema' => 's',
                  'users' => 's',
                  'permissions' => 's',
                  'tags' => 's',
                  'qoptions' => 's',
                ],
            ]
            ,
            "gerente"=>
            [
                "ler"=>["painel"=>"s","transparencia"=>"s","cad-social"=>"s","cad-topografico"=>"s","familias"=>"s","quadras"=>"s","lotes"=>"s","beneficiarios"=>"s","bairros"=>"s","etapas"=>"s","escolaridades"=>"s","estado-civil"=>"s","relatorios"=>"n","relatorios_social"=>"n","relatorios_acessos"=>"n","documentos"=>"s","config"=>"s","sistema"=>"n","users"=>"s","permissions"=>"s"],
                "ler_arquivos"=>["cad-social"=>"s","cad-topografico"=>"s","familias"=>"s","quadras"=>"s","lotes"=>"s","beneficiarios"=>"s","bairros"=>"s","etapas"=>"s","escolaridades"=>"s","estado-civil"=>"s","relatorios"=>"s","relatorios_social"=>"s","relatorios_acessos"=>"s","documentos"=>"s","qoptions"=>"s","config"=>"s","sistema"=>"s","users"=>"s","permissions"=>"s"],
                "create"=>["familias"=>"s","quadras"=>"s","lotes"=>"s","bairros"=>"s","beneficiarios"=>"s","etapas"=>"s","escolaridades"=>"s","estado-civil"=>"s","relatorios_social"=>"s","relatorios_acessos"=>"s","sistema"=>"s","users"=>"s","permissions"=>"s","documentos"=>"s"],
                "update"=>["familias"=>"s","quadras"=>"s","lotes"=>"s","bairros"=>"s","beneficiarios"=>"s","etapas"=>"s","escolaridades"=>"s","estado-civil"=>"s","relatorios_social"=>"s","relatorios_acessos"=>"s","sistema"=>"s","users"=>"s","permissions"=>"s","documentos"=>"s"],
                "delete"=>["familias"=>"s","quadras"=>"s","lotes"=>"s","bairros"=>"s","beneficiarios"=>"s","etapas"=>"s","escolaridades"=>"s","estado-civil"=>"s","relatorios_social"=>"s","relatorios_acessos"=>"s","sistema"=>"s","users"=>"s","permissions"=>"s","documentos"=>"s"]
            ],
        ];
        DB::table('permissions')->truncate();
        DB::table('permissions')->insert([
            [
                'name'=>'Master',
                'description'=>'Desenvolvedores',
                'redirect_login'=>'/home',
                'active'=>'s',
                'id_menu'=>json_encode($arrPermiss['master']),
            ],
            [
                'name'=>'Administrador',
                'description'=>'Administradores do sistema',
                'redirect_login'=>'/home',
                'active'=>'s',
                'id_menu'=>json_encode($arrPermiss['admin']),
            ],
            [
                'name'=>'Gerente',
                'description'=>'Gerente do sistema menos que administrador secundário',
                'redirect_login'=>'/home',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
            [
                'name'=>'Escritório',
                'description'=>'Pessoas do escritório',
                'redirect_login'=>'/home',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
            [
                'name'=>'Clientes',
                'description'=>'Somente clientes, Sem privilêgios de administração acesso a área restrita do site',
                'redirect_login'=>'/home',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
        ]);
    }
}
